<?php

namespace Sf\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FoyerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoyerRepository extends EntityRepository
{
	public function getSelectList($user)
	{
		$qb = $this->createQueryBuilder('a');

		$qb->join('a.users', 'u')
		->where('u.id = :user')
		->setParameter('user', $user);

    // Et on retourne simplement le QueryBuilder, et non la Query, attention
		return $qb;
	}
}
