<?php

namespace Sf\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FoyerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoyerRepository extends EntityRepository
{
}
