sfandroid_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SfandroidBundle:Default:index }

sfandroid_connexion:
    pattern:  /connexion
    defaults: { _controller: SfandroidBundle:Default:connexion }
