parameters:
#    sfandroid.example.class: Sf\androidBundle\Example

services:
#    sfandroid.example:
#        class: %sfandroid.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
