parameters:
#    sf_loan.example.class: Sf\Bundle\LoanBundle\Example

services:
#    sf_loan.example:
#        class: %sf_loan.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
