<?php

namespace Sf\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnswerUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerUserRepository extends EntityRepository
{
}
