task:
    pattern:  /
    defaults: { _controller: "SfTodoBundle:Task:index" }

task_show:
    pattern:  /{id}/show
    defaults: { _controller: "SfTodoBundle:Task:show" }

task_showEvent:
    pattern:  /{id}/showEvent
    defaults: { _controller: "SfTodoBundle:Task:showEvent" }

task_new:
    pattern:  /{visible}/new
    defaults: { _controller: "SfTodoBundle:Task:new" }

task_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SfTodoBundle:Task:edit" }

task_update:
    pattern:  /{id}/update
    defaults: { _controller: "SfTodoBundle:Task:update" }
    requirements: { _method: post|put }

task_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SfTodoBundle:Task:delete" }

task_calendar:
    pattern: /calendar
    defaults: { _controller:"SfTodoBundle:Task:calendar" }

task_showCalendarPrevious:
    pattern:  /{month}/{year}/previous
    defaults: { _controller: "SfTodoBundle:Task:CalendarPrevious" }

task_showCalendarNext:
    pattern:  /{month}/{year}/next
    defaults: { _controller: "SfTodoBundle:Task:CalendarNext" }

task_status:
    pattern: /{status}
    defaults: { _controller:"SfTodoBundle:Task:findStatus" }

task_validate:
    pattern: /validate/{id}
    defaults: { _controller:"SfTodoBundle:Task:validate" }

