<?php

namespace Sf\LoanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanRepository extends EntityRepository
{
  public function getPersonnalList($foyer, $user)
  {
    $qb = $this->_em->createQueryBuilder();

    $qb->select('a')
    ->from('SfLoanBundle:Loan', 'a')
    ->where('a.foyer = :foyer')
    ->setParameter('foyer', $foyer)
    ->andWhere('a.createdBy = :createdBy or a.borrower = :user or a.lender = :user')
    ->setParameter('createdBy', $user->getId())
    ->setParameter('user', $user)
    ;

    return $qb->getQuery()
              ->getResult();
  }
}