contact:
    pattern:  /
    defaults: { _controller: "SfContactBundle:Contact:index" }

contact_show:
    pattern:  /{id}/show
    defaults: { _controller: "SfContactBundle:Contact:show" }

contact_new:
    pattern:  /new
    defaults: { _controller: "SfContactBundle:Contact:new" }

contact_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SfContactBundle:Contact:edit" }

contact_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SfContactBundle:Contact:delete" }

contact_search:
    pattern:  /search
    defaults: { _controller: "SfContactBundle:Contact:search" }