parameters:
#    sf_contact.example.class: Sf\ContactBundle\Example

services:
#    sf_contact.example:
#        class: %sf_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
