<?php

namespace Sf\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
	public function getSelectList($foyer, $month, $year)
  {
    $qb = $this->_em->createQueryBuilder();

    $startmonth = new \DateTime();
    $startmonth->setDate($year, $month, '1');
    $endmonth = new \DateTime();
    $endmonth->setDate($year, ($month+1), '1');


  	$qb->select('a')
  	   ->from('SfTodoBundle:Task', 'a')
  	   ->where('a.foyer = :foyer')
       ->setParameter('foyer', $foyer)
       ->andWhere('a.deadline >= :startmonth')
       ->setParameter('startmonth', $startmonth)
       ->andWhere('a.deadline < :endmonth')
       ->setParameter('endmonth', $endmonth)
       ->orderBy('a.deadline', 'ASC');

    // Et on retourne simplement le QueryBuilder, et non la Query, attention
    return $qb->getQuery()
              ->getResult();
  }
}
