shoppinglist:
    pattern:  /
    defaults: { _controller: "SfShoppingBundle:ShoppingList:index" }

shoppinglist_show:
    pattern:  /{id}/show
    defaults: { _controller: "SfShoppingBundle:ShoppingList:show" }

shoppinglist_new:
    pattern:  /new
    defaults: { _controller: "SfShoppingBundle:ShoppingList:new" }

shoppinglist_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SfShoppingBundle:ShoppingList:edit" }

shoppinglist_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SfShoppingBundle:ShoppingList:delete" }

article_new:
    pattern: /{id}/{page}/new
    defaults: { _controller: "SfShoppingBundle:Article:new" }

article_edit:
    pattern: /{id}/editA
    defaults: { _controller: "SfShoppingBundle:Article:edit" }

article_delete:
    pattern: /{id}/deleteA
    defaults: { _controller: "SfShoppingBundle:Article:delete" }

shoppinglist_private:
    pattern:  /private
    defaults: { _controller: "SfShoppingBundle:ShoppingPrivateList:index" }

shoppinglist_privatenew:
    pattern:  /privatenew
    defaults: { _controller: "SfShoppingBundle:ShoppingPrivateList:new" }

shoppinglist_privateedit:
    pattern:  /{id}/privateedit
    defaults: { _controller: "SfShoppingBundle:ShoppingPrivateList:edit" }