<?php

namespace Sf\ShoppingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingListRepository extends EntityRepository
{
  public function getPersonnalList($foyer, $user, $private)
  {
    $qb = $this->_em->createQueryBuilder();

    $qb->select('a')
    ->from('SfShoppingBundle:ShoppingList', 'a')
    ->leftjoin('a.users', 'u')
    ->where('a.foyer = :foyer')
    ->setParameter('foyer', $foyer)
    ->andWhere('a.private = :private')
    ->setParameter('private', $private)
    ->andWhere('a.createdBy = :createdBy or u = :user')
    ->setParameter('createdBy', $user->getId())
    ->setParameter('user', $user)
    ->orderBy('a.deadline', 'ASC')
    ;

    return $qb->getQuery()
              ->getResult();
  }
}