parameters:
#    sf_user.example.class: Sf\UserBundle\Example

services:
#    sf_user.example:
#        class: %sf_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sf_user.registration.form.type:
        class: Sf\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sf_user_registration }